version: 1
disable_existing_loggers: no  
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(funcName)s - %(levelname)s - %(message)s"
 
root: 
    level: DEBUG
    handlers: [console,info_file_handler,error_file_handler]
 

handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: C:\TEMP\moodys\bccl-202215.01.09-RELEASE\scripts\logs\info.log
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: C:\TEMP\moodys\bccl-202215.01.09-RELEASE\scripts\logs\error.log
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8